Spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/seroslaw/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

        # native:
          # search-locations: "file:///Users//seroslaw//Documents//config"
          # search-locations: "classpath:/config"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45ASD57VDSCV123VCXV676"

server:
  port: 8071

